name: CI
on:
  pull_request:

jobs:
  changes:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      trix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          json: true

      - name: List all changed dirs
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}

  # Try alsoo JSON and things like that
  # test-run:
  #   runs-on: ubuntu-latest
