name: CI
on:
  pull_request:

jobs:
  changes:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      trix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true

      - name: List all changed dirs
        run: |
          aux_dirs=()
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $dir == "." || $dir == "main_dir" ]]; then
              echo "Got a main change!"
            elif [[ $dir == "aux_dirs/"*  ]]; then
              aux_dirs+=($dir)
              echo "Got a aux change!"
            fi
            echo "$dir was changed"
            echo "***********************"
          done

          echo "All aux dirs changed: $aux_dirs"

# If we have . or src or tests -> do base test
# if starts with flows/ -> add to flows array
# if starts with o


  # # Try alsoo JSON and things like that
  # test-run:
  #   runs-on: ubuntu-latest
