name: CI
on:
  pull_request:

jobs:
  changes:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      trix: ${{ steps.kek.outputs.kek }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true

      - name: List all changed dirs
        id: kek
        run: |
          auxy_dirs=()
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $dir == "." || $dir == "main_dir" ]]; then
              echo "Got a main change!"
            elif [[ $dir == "aux_dirs/"* ]]; then
              auxy_dirs+=( "$dir" )
              echo "Got a aux change!"
            fi
            echo "$dir was changed"
            echo "***********************"
          done

          aux_dirs=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${auxy_dirs[@]}")
          echo "kek={\"kk\":$aux_dirs}" >> $GITHUB_OUTPUT



# If we have . or src or tests -> do base test
# if starts with flows/ -> add to flows array
# if starts with o


  # # Try alsoo JSON and things like that
  test-run:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix: ${{fromJson(needs.changes.outputs.trix)}}
    steps:
    - run: echo ${{ matrix.kk }}
